### ISSUE TITLE
Minimum contig coverage and length

### ISSUE THREAD

**Issue by nbawe** [tseemann/shovill#134]
First of all this issue is more like help wanted than issue. I have questions regarding two parameters:
1) Whats the reason behind minimum contig coverage (default: 2)?
2) How to choose minimum contig length? 
I have read to discard contigs < 200;500;1000bp - is there some kind rule of thumb to do so?

**Comment by tseemann** [comment]
1,  Spades is a bit confusing about that "kmer coverage" measurement. my experience just showed that contigs with coverage 0 to 1.9 were junk. But you can set it to 0 and do your own filtering.

2, By default I choose `--minlen = (0.5 * average read length)`. this idea was to strike a balance of useful contigs versus junk contigs. we have data from 50bp to 300bp so needed to be 'dynamic'. 200bp is a common standard because that is the minimum contig size NCBI will accept. You can set to 0 and post-filter depending on the downstream application.

**Comment by nbawe** [comment]
Thank you!

**Comment by nbawe** [comment]
@tseemann you are completely right:
1) I did blastn search on contigs with < 2.0 coverage and they are junk e.g. not belonging to the sequenced organism. 
2) I also got some high coverage conting assigned to different organism using megablast, but blastn gives some similarity to expected organism.

As I have never uploaded genomes to NCBI could you help me:
1) I should remove contigs with less than 200bp and coverage <2 - thats correct?
2) Should I remove high coverage contigs (I have two contigs with coverage 19 and 9) which megablast assigned to different organism?
3) How to blast large contings - NCBI webinterface gives error?

Thank you for your time

**Comment by tseemann** [comment]
High coverage contigs can be many things
* contamintaion 
* controls eg. phiX
* genomic repeats eg. transposon
* plasmid ie. high copy numer
