### ISSUE TITLE
Using Shovill with 4x2 sequence reads per sample!

### ISSUE THREAD

**Issue by nbawe** [tseemann/shovill#144]
Hello,
I have NextSeq500 sequence reads there are 4x2(forward-reverse) per sample. Is there anyway to use Shovill with 8 reads per sample?

**Comment by tseemann** [comment]
You should ask your sequencing provider to reconfigure their `bcl2fastq` to produce only 2 files for you instead of 8.

Until then, you can just concatentate them into a single file. You don't even need to decompress and recompress.

ie.
````
cat blah*_R1*q.gz > blah_R1.fastq.gz
cat blah*_R2*q.gz > blah_R2.fastq.gz
 ```
Just make sure the * only matches the `L001` to `L004` fot the sample you want  (I called it `blah` here).

**Comment by nbawe** [comment]
Thank you @tseemann, but excuse me my ignorance I did not understand how to write the commands.

For example I have following filenames:
1) Sample1_S34_L001_R1_001.fastq.qz
2) Sample1_S34_L001_R2_001.fastq.qz
3) Sample1_S34_L002_R1_001.fastq.qz
4) Sample1_S34_L002_R2_001.fastq.qz
5) Sample1_S34_L003_R1_001.fastq.qz
6) Sample1_S34_L003_R2_001.fastq.qz
7) Sample1_S34_L004_R1_001.fastq.qz
8) Sample1_S34_L004_R2_001.fastq.qz

Then the commands would be? Do I need to rename the files?

**Comment by nbawe** [comment]
I just found out that spades can concatenate the sequences itself [spades issue #22](https://github.com/ablab/spades/issues/22#issuecomment-303617710)
